### ISSUE TITLE
Items based currency only

### ISSUE THREAD

**Issue by DIKINGVFX** [Tweetzy/Markets#32]
Hi everyone, 
First of all thanks for your amazing work! 

However, I was wondering if it is possible to add the option to only use items based currency and remove the option to use vault currency for instance ? 

Thanks in advance !

**Comment by kiranhart** [comment]
Hey, I was going to work on this, but realized it's already a feature. The setting is called: "use item only", set that to true, then to specify the item, look for "default item selection" in the config and adjust it's value.

**Comment by kiranhart** [comment]
I'll close this issue for now, but if it's not how you wanted, just re-open/re-create

**Comment by DIKINGVFX** [comment]
Hi, sorry for the late reply.

Actually, there is a setting called 'use item only.' However, even when I set it to true, I still have the option to use the vault economy, which is very inconvenient for a prison server.

Thanks in advance!
