### ISSUE TITLE
When using the Offers the object that is delivered is different

### ISSUE THREAD

**Issue by WasaTG** [Tweetzy/Markets#39]
**Describe the bug**
When a user places an item to sell in the market and another user buys it, the item that is delivered is exactly the same item that the seller placed in the beginning.

The problem is that when a user makes an offer instead of buying it, if the seller accepts the offer, item that the buyer receives is different from the item that the seller put up for sale.

**To Reproduce**

- Describe how to reproduce this bug: EX.

1. The seller puts an item on the market for sale.

2. The user who wants to buy that item, instead of making the purchase, chooses to make an offer

3. The seller accepts the offer, so the item is sold, but since it is an offer and not a direct purchase, the buyer receives his item in the "Collect Payments" section.

4. That item that the buyer receives is different from the item that the seller originally put up for sale (it is identical in terms of characteristics, but for some reason it cannot be stacked with other original items)

**Expected behavior**
The received item should be able to be stacked with other items that are the same. But for some reason when the item goes through an "Offer" something changes

**Screenshots**
Video where exactly the problem is shown

https://youtu.be/B0zWkOnNY5M

**Server Information (please complete the following information):**

- Provide the server version | 1.18.2 and Java 17
- Provide the server jar (ex. paper/spigot) | paper-1.13.2-657.jar
- Plugin Version | 2.8.1

**Comment by kiranhart** [comment]
thanks for the report
