### ISSUE TITLE
The rating/review feature dosnt work 

### ISSUE THREAD

**Issue by Sandukhan** [Tweetzy/Markets#43]
**Describe the bug**
With the latest version of markets (2.9.0). Rating/reviewing shops does not work anymore. Selecting a star causes some issues and a new rating cant be confirmed. In markets  2.8.1 it worked.

**Server Information (please complete the following information):**

- Paper 1.20.1, Java 17
- paper-1.20.1-169.jar
- markets 2.9.0

**Comment by kiranhart** [comment]
+ Resolved v2.10.0
