### ISSUE TITLE
Duplicate Unstack items

### ISSUE THREAD

**Issue by lee3kfc** [Tweetzy/Markets#6]
Duplicate Bug Report
1. add unstack item to the bank multiple times. (hold unstack item and command /markets bank add)
2. open GUI and go to bank page, click the item which you added.
3. type exact same number of the items.(if you added 3, type 3)
4. bank still has -1 numbers of items you added. repeat 2 and 3.
5. now you have double numbers of items.

paper-1.19.2-201.jar
Markets - The Ultimate Player Shop [Paid] 1.33.3

**Comment by arturek1666** [comment]
I had record it, looks like this, while issue is similar I just had to add /markets bank add -a and had like 64x3 stacks +8 in inventory when doing it, as long as it's more than 64 items it will duplicate.
Video:
https://youtu.be/DbA2XSY9ryI
I had message author and got respond in spigot but yeah next time will check if someone already got the issue.
