### ISSUE TITLE
IMPORTANT - Market sorting

### ISSUE THREAD

**Issue by Pexep** [Tweetzy/Markets#77]
**Describe Feature**
It would be very good to be able to sort markets, in all markets menu, by their ratings.

**Comment by RSLuke** [comment]
Any news ? 
It would allow to have the plugin more active for players, by sending inactives markets on next pages

**Comment by kiranhart** [comment]
> Any news ? It would allow to have the plugin more active for players, by sending inactives markets on next pages

Just been a bit busy with other things. Also been finishing up shops v4 and I'll get back to reports on other stuff.
